### ISSUE TITLE
Contradict dependencies

### ISSUE THREAD

**Issue by DeweiHu** [bowang-lab/ECG-FM#1]
Hello, thanks for sharing your great work! When I tried to implement your model, I found some problems with regard to the dependencies. I setup the environment as it is indicated in **fairseq-signals**. However, when I run the inference code, there is a bug indicating that: 
```
from hydra.core.config_store import ConfigStore requires hydra-core >= 1.1.0
hydra-core 1.1.0 requires omegaconf=2.1.*
fairseq-signals 1.0.0a0 requires hydra-core < 1.1
fairseq-signals 1.0.0a0 requires omegaconf < 2.1
```
There is a conflict in the required package version. I wonder if you can share your environment in .yaml? 

Thanks!

**Comment by tesselhuib** [comment]
I am using omegaconf 2.1.0, hydra-core 1.0.7 and python 3.8.19 and with that I can run the inference code. Only issue for me was that in fairseq-signals/data/data_utils.py I had to add the line "indices = indices.astype(np.int64)" because otherwise i would get a dtype error.

**Comment by DeweiHu** [comment]
Thanks for sharing! I will try this out.

**Comment by Jwoo5** [comment]
Did you install those packages using `python setup.py build_ext --inplace` in the fairseq-signals repository?
I believe it should not have a such dependency issue if you followed the installation guide for the fairseq-signals.
