### ISSUE TITLE
Question of importing fairesq 

### ISSUE THREAD

**Issue by FUminlee** [bowang-lab/ECG-FM#3]
When I try:

**"from fairesq_signals.utils.store import MemmapReader"**

I met some bugs.

When I construct an env using python=3.8, I will got the error message:

**ValueError: mutable default <class 'fairseq_signals.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory**

This error could be fixed with I use python=3.9, but I will meet another error:

**ImportError: cannot import name 'II' from 'omegaconf' (/Users/fuminli/anaconda3/envs/fairseq_signals_env2/lib/python3.9/site-packages/omegaconf/__init__.py)**

Adjusting the version of omegaconf failed to fix the problem.

Could you please take a look at this problem? Thanks a lot!

**Comment by KadenMc** [comment]
I have contacted the owner of the `fairseq_signals` repository and will respond if they provide insight, but I do suggest submitting this issue directly to [fairseq-signals](https://github.com/Jwoo5/fairseq-signals/issues).

Thank you for your patience!
