### ISSUE TITLE
Result on PTB-XL

### ISSUE THREAD

**Issue by ndhuynh02** [bowang-lab/ECG-FM#5]
First of all, I want to congrats you on this amazing work. However, I am a bit curious. Since the results shown in the paper is the private dataset. I am wondering how the model performs on public dataset like PTB-XL. Can you provide me the results?

**Comment by KadenMc** [comment]
Hello and thank you for your interest in our work!

Unfortunately, we are not currently validating on PTB-XL at this time, so I am unable to share such results.

The final publication will be such that the experiments (on public datasets) are entirely reproducible! So, you may need to hang tight for that - sorry for the inconvenience.

**Comment by ndhuynh02** [comment]
I have a another question. How is the dataset processed in the finetuning phase. As from [README](https://github.com/bowang-lab/ECG-FM/blob/3f764c354297ce61b8123c800d664478e390fba9/README.md?plain=1#L39), the model is finetuned on Physionet2021, and this dataset is a combination of multiple data. However, as far as I know, Physionet2021 doesn't provide data splitting for training, validation and test. In addition, the PTB-XL dataset (which is also included in Physionet2021) is usually used to verify the model performance. Does this mean there is a chance that this finetuned checkpoint has already seen some of the testset in PTB-XL?
